// <auto-generated />
using System;
using Gijgo.Asp.NetCore.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace Gijgo.AspNetCore.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20190111135054_InitialCreate")]
    partial class InitialCreate
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.2.0-rtm-35687")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("Gijgo.Asp.NET.Examples.Models.Entities.Location", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<bool>("Checked");

                    b.Property<string>("FlagUrl");

                    b.Property<string>("Name");

                    b.Property<int>("OrderNumber");

                    b.Property<int?>("ParentID");

                    b.Property<long?>("Population");

                    b.HasKey("ID");

                    b.HasIndex("ParentID");

                    b.ToTable("Locations");

                    b.HasData(
                        new
                        {
                            ID = 1,
                            Checked = false,
                            Name = "Asia",
                            OrderNumber = 1
                        },
                        new
                        {
                            ID = 2,
                            Checked = false,
                            FlagUrl = "http://code.gijgo.com/flags/24/China.png",
                            Name = "China",
                            OrderNumber = 1,
                            ParentID = 1,
                            Population = 1373541278L
                        },
                        new
                        {
                            ID = 3,
                            Checked = false,
                            FlagUrl = "http://code.gijgo.com/flags/24/Japan.png",
                            Name = "Japan",
                            OrderNumber = 2,
                            ParentID = 1,
                            Population = 126730000L
                        },
                        new
                        {
                            ID = 4,
                            Checked = false,
                            FlagUrl = "http://code.gijgo.com/flags/24/Mongolia.png",
                            Name = "Mongolia",
                            OrderNumber = 3,
                            ParentID = 1,
                            Population = 3081677L
                        },
                        new
                        {
                            ID = 5,
                            Checked = false,
                            Name = "North America",
                            OrderNumber = 2
                        },
                        new
                        {
                            ID = 6,
                            Checked = false,
                            FlagUrl = "http://code.gijgo.com/flags/24/United%20States%20of%20America(USA).png",
                            Name = "USA",
                            OrderNumber = 1,
                            ParentID = 5,
                            Population = 325145963L
                        },
                        new
                        {
                            ID = 7,
                            Checked = false,
                            Name = "California",
                            OrderNumber = 1,
                            ParentID = 6,
                            Population = 39144818L
                        },
                        new
                        {
                            ID = 8,
                            Checked = false,
                            Name = "Florida",
                            OrderNumber = 2,
                            ParentID = 6,
                            Population = 20271272L
                        },
                        new
                        {
                            ID = 9,
                            Checked = false,
                            FlagUrl = "http://code.gijgo.com/flags/24/canada.png",
                            Name = "Canada",
                            OrderNumber = 2,
                            ParentID = 5,
                            Population = 35151728L
                        },
                        new
                        {
                            ID = 10,
                            Checked = false,
                            FlagUrl = "http://code.gijgo.com/flags/24/mexico.png",
                            Name = "Mexico",
                            OrderNumber = 3,
                            ParentID = 5,
                            Population = 119530753L
                        },
                        new
                        {
                            ID = 11,
                            Checked = false,
                            Name = "South America",
                            OrderNumber = 3
                        },
                        new
                        {
                            ID = 12,
                            Checked = false,
                            FlagUrl = "http://code.gijgo.com/flags/24/brazil.png",
                            Name = "Brazil",
                            OrderNumber = 1,
                            ParentID = 11,
                            Population = 207350000L
                        },
                        new
                        {
                            ID = 13,
                            Checked = false,
                            FlagUrl = "http://code.gijgo.com/flags/24/argentina.png",
                            Name = "Argentina",
                            OrderNumber = 2,
                            ParentID = 11,
                            Population = 43417000L
                        },
                        new
                        {
                            ID = 14,
                            Checked = false,
                            FlagUrl = "http://code.gijgo.com/flags/24/colombia.png",
                            Name = "Colombia",
                            OrderNumber = 3,
                            ParentID = 11,
                            Population = 49819638L
                        },
                        new
                        {
                            ID = 15,
                            Checked = false,
                            Name = "Europe",
                            OrderNumber = 4
                        },
                        new
                        {
                            ID = 16,
                            Checked = false,
                            FlagUrl = "http://code.gijgo.com/flags/24/england.png",
                            Name = "England",
                            OrderNumber = 1,
                            ParentID = 15,
                            Population = 54786300L
                        },
                        new
                        {
                            ID = 17,
                            Checked = false,
                            FlagUrl = "http://code.gijgo.com/flags/24/germany.png",
                            Name = "Germany",
                            OrderNumber = 2,
                            ParentID = 15,
                            Population = 82175700L
                        },
                        new
                        {
                            ID = 18,
                            Checked = false,
                            FlagUrl = "http://code.gijgo.com/flags/24/bulgaria.png",
                            Name = "Bulgaria",
                            OrderNumber = 3,
                            ParentID = 15,
                            Population = 7101859L
                        },
                        new
                        {
                            ID = 19,
                            Checked = false,
                            FlagUrl = "http://code.gijgo.com/flags/24/poland.png",
                            Name = "Poland",
                            OrderNumber = 4,
                            ParentID = 15,
                            Population = 38454576L
                        });
                });

            modelBuilder.Entity("Gijgo.Asp.NET.Examples.Models.Entities.Player", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("CountryID");

                    b.Property<DateTime>("DateOfBirth")
                        .HasColumnType("Date");

                    b.Property<bool>("IsActive");

                    b.Property<string>("Name");

                    b.Property<int>("OrderNumber");

                    b.Property<string>("PlaceOfBirth");

                    b.HasKey("ID");

                    b.HasIndex("CountryID");

                    b.ToTable("Players");

                    b.HasData(
                        new
                        {
                            ID = 1,
                            CountryID = 18,
                            DateOfBirth = new DateTime(1966, 2, 8, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsActive = false,
                            Name = "Hristo Stoichkov",
                            OrderNumber = 1,
                            PlaceOfBirth = "Plovdiv, Bulgaria"
                        },
                        new
                        {
                            ID = 2,
                            CountryID = 12,
                            DateOfBirth = new DateTime(1976, 9, 18, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsActive = false,
                            Name = "Ronaldo Luís Nazário de Lima",
                            OrderNumber = 2,
                            PlaceOfBirth = "Rio de Janeiro, Brazil"
                        },
                        new
                        {
                            ID = 3,
                            CountryID = 16,
                            DateOfBirth = new DateTime(1966, 6, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsActive = false,
                            Name = "David Platt",
                            OrderNumber = 3,
                            PlaceOfBirth = "Chadderton, Lancashire, England"
                        },
                        new
                        {
                            ID = 4,
                            CountryID = 17,
                            DateOfBirth = new DateTime(1986, 3, 27, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsActive = true,
                            Name = "Manuel Neuer",
                            OrderNumber = 4,
                            PlaceOfBirth = "Gelsenkirchen, West Germany"
                        },
                        new
                        {
                            ID = 5,
                            CountryID = 14,
                            DateOfBirth = new DateTime(1991, 7, 12, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsActive = true,
                            Name = "James Rodríguez",
                            OrderNumber = 5,
                            PlaceOfBirth = "Cúcuta, Colombia"
                        },
                        new
                        {
                            ID = 6,
                            CountryID = 18,
                            DateOfBirth = new DateTime(1981, 1, 30, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsActive = false,
                            Name = "Dimitar Berbatov",
                            OrderNumber = 6,
                            PlaceOfBirth = "Blagoevgrad, Bulgaria"
                        },
                        new
                        {
                            ID = 7,
                            CountryID = 19,
                            DateOfBirth = new DateTime(1988, 8, 21, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsActive = true,
                            Name = "Robert Lewandowski",
                            OrderNumber = 7,
                            PlaceOfBirth = "Warsaw, Poland"
                        });
                });

            modelBuilder.Entity("Gijgo.Asp.NET.Examples.Models.Entities.PlayerTeam", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("Apps");

                    b.Property<int>("FromYear");

                    b.Property<int>("Goals");

                    b.Property<int>("PlayerID");

                    b.Property<string>("Team");

                    b.Property<int>("ToYear");

                    b.HasKey("ID");

                    b.HasIndex("PlayerID");

                    b.ToTable("PlayerTeams");

                    b.HasData(
                        new
                        {
                            ID = 1,
                            Apps = 32,
                            FromYear = 1982,
                            Goals = 14,
                            PlayerID = 1,
                            Team = "Hebros Harmanli",
                            ToYear = 1984
                        },
                        new
                        {
                            ID = 2,
                            Apps = 119,
                            FromYear = 1984,
                            Goals = 81,
                            PlayerID = 1,
                            Team = "CSKA Sofia",
                            ToYear = 1990
                        },
                        new
                        {
                            ID = 3,
                            Apps = 149,
                            FromYear = 1990,
                            Goals = 77,
                            PlayerID = 1,
                            Team = "Barcelona",
                            ToYear = 1995
                        },
                        new
                        {
                            ID = 4,
                            Apps = 23,
                            FromYear = 1995,
                            Goals = 5,
                            PlayerID = 1,
                            Team = "Parma",
                            ToYear = 1996
                        },
                        new
                        {
                            ID = 5,
                            Apps = 26,
                            FromYear = 1996,
                            Goals = 7,
                            PlayerID = 1,
                            Team = "Barcelona",
                            ToYear = 1998
                        },
                        new
                        {
                            ID = 6,
                            Apps = 4,
                            FromYear = 1998,
                            Goals = 1,
                            PlayerID = 1,
                            Team = "CSKA Sofia",
                            ToYear = 1998
                        },
                        new
                        {
                            ID = 7,
                            Apps = 2,
                            FromYear = 1998,
                            Goals = 1,
                            PlayerID = 1,
                            Team = "Al-Nassr",
                            ToYear = 1998
                        },
                        new
                        {
                            ID = 8,
                            Apps = 27,
                            FromYear = 1998,
                            Goals = 12,
                            PlayerID = 1,
                            Team = "Kashiwa Reysol",
                            ToYear = 1999
                        },
                        new
                        {
                            ID = 9,
                            Apps = 51,
                            FromYear = 2000,
                            Goals = 17,
                            PlayerID = 1,
                            Team = "Chicago Fire",
                            ToYear = 2002
                        },
                        new
                        {
                            ID = 10,
                            Apps = 21,
                            FromYear = 2003,
                            Goals = 5,
                            PlayerID = 1,
                            Team = "D.C. United",
                            ToYear = 2003
                        },
                        new
                        {
                            ID = 11,
                            Apps = 14,
                            FromYear = 1993,
                            Goals = 12,
                            PlayerID = 2,
                            Team = "Cruzeiro",
                            ToYear = 1994
                        },
                        new
                        {
                            ID = 12,
                            Apps = 46,
                            FromYear = 1994,
                            Goals = 42,
                            PlayerID = 2,
                            Team = "PSV",
                            ToYear = 1996
                        },
                        new
                        {
                            ID = 13,
                            Apps = 37,
                            FromYear = 1996,
                            Goals = 34,
                            PlayerID = 2,
                            Team = "Barcelona",
                            ToYear = 1997
                        },
                        new
                        {
                            ID = 14,
                            Apps = 68,
                            FromYear = 1997,
                            Goals = 49,
                            PlayerID = 2,
                            Team = "Inter Milan",
                            ToYear = 2002
                        },
                        new
                        {
                            ID = 15,
                            Apps = 127,
                            FromYear = 2002,
                            Goals = 83,
                            PlayerID = 2,
                            Team = "Real Madrid",
                            ToYear = 2007
                        },
                        new
                        {
                            ID = 16,
                            Apps = 20,
                            FromYear = 2007,
                            Goals = 9,
                            PlayerID = 2,
                            Team = "Milan",
                            ToYear = 2008
                        },
                        new
                        {
                            ID = 17,
                            Apps = 31,
                            FromYear = 2009,
                            Goals = 18,
                            PlayerID = 2,
                            Team = "Corinthians",
                            ToYear = 2011
                        },
                        new
                        {
                            ID = 18,
                            Apps = 134,
                            FromYear = 1985,
                            Goals = 56,
                            PlayerID = 3,
                            Team = "Crewe Alexandra",
                            ToYear = 1988
                        },
                        new
                        {
                            ID = 19,
                            Apps = 121,
                            FromYear = 1988,
                            Goals = 50,
                            PlayerID = 3,
                            Team = "Aston Villa",
                            ToYear = 1991
                        },
                        new
                        {
                            ID = 20,
                            Apps = 29,
                            FromYear = 1991,
                            Goals = 11,
                            PlayerID = 3,
                            Team = "Bari",
                            ToYear = 1992
                        },
                        new
                        {
                            ID = 21,
                            Apps = 16,
                            FromYear = 1992,
                            Goals = 3,
                            PlayerID = 3,
                            Team = "Juventus",
                            ToYear = 1993
                        },
                        new
                        {
                            ID = 22,
                            Apps = 55,
                            FromYear = 1993,
                            Goals = 17,
                            PlayerID = 3,
                            Team = "Sampdoria",
                            ToYear = 1995
                        },
                        new
                        {
                            ID = 23,
                            Apps = 88,
                            FromYear = 1995,
                            Goals = 13,
                            PlayerID = 3,
                            Team = "Arsenal",
                            ToYear = 1998
                        },
                        new
                        {
                            ID = 24,
                            Apps = 5,
                            FromYear = 1999,
                            Goals = 1,
                            PlayerID = 3,
                            Team = "Nottingham Forest",
                            ToYear = 2001
                        });
                });

            modelBuilder.Entity("Gijgo.Asp.NET.Examples.Models.Entities.Location", b =>
                {
                    b.HasOne("Gijgo.Asp.NET.Examples.Models.Entities.Location", "Parent")
                        .WithMany("Children")
                        .HasForeignKey("ParentID");
                });

            modelBuilder.Entity("Gijgo.Asp.NET.Examples.Models.Entities.Player", b =>
                {
                    b.HasOne("Gijgo.Asp.NET.Examples.Models.Entities.Location", "Country")
                        .WithMany()
                        .HasForeignKey("CountryID")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("Gijgo.Asp.NET.Examples.Models.Entities.PlayerTeam", b =>
                {
                    b.HasOne("Gijgo.Asp.NET.Examples.Models.Entities.Player", "Player")
                        .WithMany("Teams")
                        .HasForeignKey("PlayerID")
                        .OnDelete(DeleteBehavior.Cascade);
                });
#pragma warning restore 612, 618
        }
    }
}
